[package]
name = "ribbit"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
clap = { version = "4.0.19", features = ["derive"] }
crc32fast = "1.3.2"
futuresdr = { path = "../..", features = ["aaronia_http", "soapy"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rustfft = "6.1"
